---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-files-cm
  namespace: {{ .Release.Namespace | quote }}
data:
{{ range $path, $_ :=  (.Files.Glob  "files/{**}") }}
{{- $path | replace "/" "." | indent 2 }}: |
{{ $.Files.Get $path | indent 4 }}
{{ end }}