baseURL: https://example.com
waitBeforeExit: 5
debug: true
plugins:
  reload:
    - path: /
      count: 3
      intervalSeconds: 5
  require:
    # By default, this will expect status code 200
    - path: /
      statusCode: 200
      cssSelector:
        - 'title:text("Example Domain")'
        - 'body'
      antiCssSelector:
        - 'title:text("Random name")'
    # Check for a specific status code & title of the page
    - path: /this-path-should-not-exist
      statusCode: 404
