generateName: false
forceRecreate: false
annotations: {}
labels: {}
container:
  env:
    MARIADB_ROOT_USER: "root"
    # MARIADB_ROOT_PASSWORD
    MARIADB_DATABASE: "example"
  envBase64: {}
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 1Gi
    limits:
      cpu: 400m
      memory: 1024Mi
      ephemeral-storage: 2Gi
  startupProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
persistence:
  enabled: false
  local:
    # Do not enable in production!
    enabled: false
    path: "/.devspace/volumes/mysql"
  subPath: "bitnami/mariadb"
  # The rest of the values are ignored if local.enabled is true
  storageClass: "local-path"
  accessMode: "ReadWriteOnce"
  size: 5Gi
# Ref: https://github.com/bitnami/charts/blob/main/bitnami/mariadb/values.yaml
configuration: |-
  [mysqld]
  skip-name-resolve
  explicit_defaults_for_timestamp
  basedir=/opt/bitnami/mariadb
  datadir=/bitnami/mariadb/data
  plugin_dir=/opt/bitnami/mariadb/plugin
  port=3306
  socket=/opt/bitnami/mariadb/tmp/mysql.sock
  tmpdir=/opt/bitnami/mariadb/tmp
  max_allowed_packet=16M
  bind-address=*
  pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
  log-error=/opt/bitnami/mariadb/logs/mysqld.log
  character-set-server=UTF8
  collation-server=utf8_general_ci
  slow_query_log=0
  long_query_time=10.0
  
  [client]
  port=3306
  socket=/opt/bitnami/mariadb/tmp/mysql.sock
  default-character-set=UTF8
  plugin_dir=/opt/bitnami/mariadb/plugin
  
  [manager]
  port=3306
  socket=/opt/bitnami/mariadb/tmp/mysql.sock
  pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid