#!/bin/bash

# Create an s3 bucket
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install minio bitnami/minio --version 13.2.1 \
  --namespace minio \
  --create-namespace \
  --set auth.rootUser=root \
  --set auth.rootPassword=password \
  --set defaultBuckets="mybucket" \
  --set persistence.enabled=false \
  --set tls.enabled=true \
  --set tls.autoGenerated=true

# Wait for the minio pod to be ready
kubectl --namespace=minio wait --for=condition=ready pod --selector=app.kubernetes.io/name=minio --timeout=120s

# Wait for the minio service to create the bucket
sleep 10

# Helm apply the s3-push chart
helm upgrade --install s3-push . \
  --namespace=s3-push \
  --create-namespace \
  --set noVerifySSL=true \
  --set container.env.S3_ACCESS_KEY=root \
  --set container.env.S3_SECRET_KEY=password \
  --set container.env.S3_ENDPOINT=minio.minio.svc.cluster.local:9000 \
  --set container.env.S3_BUCKET=mybucket \
  --set container.env.S3_PATH=subfolder/

# Wait for the s3-push pod to be ready
kubectl --namespace=s3-push wait --for=condition=ready pod --selector=app.kubernetes.io/name=s3-push --timeout=120s

# Copy the s3-push directory to the s3-push pod
S3_PUSH_POD="$(kubectl --namespace=s3-push get pods -l app.kubernetes.io/name=s3-push -o jsonpath="{.items[0].metadata.name}")"
kubectl --namespace=s3-push cp ../s3-push/README.md "$S3_PUSH_POD":/s3-data/README.md

# Specify what to upload
kubectl --namespace=s3-push exec "$S3_PUSH_POD" -- echo "README.md" > /s3-data/.pull

# Show logs
kubectl --namespace=s3-push logs "$S3_PUSH_POD" --follow