---
apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-pod{{- if .Values.generateName }}-{{ randAlphaNum 5 | nospace | lower }}{{- end }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/instance: composer
  annotations:
    # Force recreate the pod on upgrade
    checksum.force.recreate: "{{- if .Values.forceRecreate }}{{ randAlphaNum 10 }}{{- end }}"
spec:
  containers:
    - name: composer
      image: "composer:2"
      command:
        - sleep
        - {{ .Values.waitSeconds | quote }}
  restartPolicy: Never
