---
apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-pod{{- if .Values.generateName }}-{{ randAlphaNum 5 | nospace | lower }}{{- end }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/name: composer
  annotations:
    # Force helm to recreate the pod on upgrade
    checksum.helm.recreate: "{{- if .Values.recreateHelm }}{{ randAlphaNum 10 }}{{- end }}"
spec:
  containers:
    - name: composer
      image: "composer:2"
      command:
        - sleep
        - {{ .Values.waitSeconds | quote }}
  restartPolicy: Never
