---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace | quote }}
spec:
  clusterIP: None
  ports:
    - name: "mysql"
      port: 3306
  selector:
    app.kubernetes.io/instance: mariadb-dev
