apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
  namespace: {{ .Release.Namespace | quote }}
data:
  entrypoint.sh: |
    #!/bin/bash
    set -e

    # Need to wait to allow devspace.yaml script to catch up.
    sleep 5

    # Example:
    # baseURL: https://example.com
    # waitBeforeExit: 5
    # plugins:
    #   downloader:
    #   - path: /
    #     fetch:
    #       - jpg
    #       - png
    # Will run /plugins/downloader.sh --baseURL="https://example.com" --waitBeforeExit=5 --path="/" --fetch="jpg" --fetch="png"
    # With all values URL encoded.
    {{- if .Values.debug -}}
      {{- printf "set -x;" | nindent 4 -}}
    {{- end -}}
    {{ if .Values.plugins -}}
      {{- range $plugin, $pluginValues := .Values.plugins -}}
        {{- if $pluginValues -}}
          {{- range $commandIndex, $commandObject := $pluginValues -}}
            {{- $cmd := printf "/mnt/plugins/%s.sh --baseURL=%s --waitBeforeExit=%s" $plugin (urlquery $.Values.baseURL) (urlquery $.Values.waitBeforeExit) -}}
            {{- if $.Values.debug -}}
              {{- $cmd = printf "%s --debug" $cmd -}}
            {{- end -}}
            {{- range $commandKey, $commandValue := $commandObject -}}
              {{- if kindIs "slice" $commandValue -}}
                {{- range $optionIndex, $optionObject := $commandValue -}}
                  {{- $cmd = printf "%s --%s=%s" $cmd $commandKey (urlquery $optionObject) -}}
                {{- end -}}
              {{- else -}}
                {{- $cmd = printf "%s --%s=%s" $cmd $commandKey (urlquery $commandValue) -}}
              {{- end -}}
            {{- end -}}
            {{- printf "echo; %s" $cmd | nindent 4 -}}
          {{- end -}}
        {{- end -}}
      {{- end -}}
      {{ printf "echo; echo 'All tests have successfully passed!'" | nindent 4 -}}
    {{- end }}
    {{- if .Values.debug -}}
      {{- printf "set +x;" | nindent 4 -}}
    {{- end -}}
