---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-plugins-cm
  namespace: {{ .Release.Namespace | quote }}
data:
{{ range $path, $_ :=  (.Files.Glob  "plugins/{**}") }}
{{- $path | trimPrefix "plugins/" | replace "/" "." | indent 2 }}: |
{{ $.Files.Get $path | indent 4 }}
{{ end }}
