container:
  #  env:
  #    S3_ACCESS_KEY: ""
  #    S3_SECRET_KEY: ""
  #    S3_ENDPOINT: ""
  #    S3_REGION: ""
  #    S3_BUCKET: ""
  #    S3_PATH: "" # Can be a file, directory, ".latest" or ".previous". If ends with "/", it will be treated as a directory. If .latest/.previous, it will copy the name from the file.
  env: {}
  envBase64: {}
# Maximum time to wait for the job to complete
activeDeadlineSeconds: 300
# Do not enable in production
noVerifySSL: false
